### ISSUE TITLE
Document the Use of `typescript-nameof` with `vite`

### ISSUE THREAD

**Issue by nemu69** [typescript-nameof/nameof#10]
Hi, I use an Angular app with Vite and I have nameof function not found.

Vite compiler
![image](https://github.com/typescript-nameof/nameof/assets/43633395/d8f2a8ca-1c34-482e-b828-1758163453e3)

VSCode
![image](https://github.com/typescript-nameof/nameof/assets/43633395/1147112a-a3f6-4345-a4d9-64264ea579d0)

Here git for test : [Playground](https://github.com/nemu69/angularXts-nameof)

Thanks !

**Comment by nemu69** [comment]
I found this repo : [vite-plugin-ts-name](https://github.com/Shinigami92/vite-plugin-ts-nameof) but doesn't works. I will create an issue.

**Comment by manuth** [comment]
Thanks a lot for adding the playground, that helps a lot!
I believe I found the reason for this issue to occur.

Could you please tell me whether you used some kind of guide or generator for setting up this project?

That's the very first time I get in touch with `vite`, so that's why I'm asking.

**Comment by nemu69** [comment]
Thanks to reply.
I used these 2 docs :
[vite-plugin-angular](https://analogjs.org/docs/packages/vite-plugin-angular/overview)
[vitest-plugin](https://analogjs.org/docs/features/testing/vitest)

Honestly, that's not very detailed.
Good luck

**Comment by nemu69** [comment]
As expected, I created a issue on vite-plugin-ts-nameof
https://github.com/Shinigami92/vite-plugin-ts-nameof/issues/113#issue-2219286178

**Comment by manuth** [comment]
Alright then
So first things first:
TypeScript highlighting the `nameof` calls as errors is because of the TypeScript configuration:
https://github.com/nemu69/angularXts-nameof/blob/main/tsconfig.json#L47

According to the TypeScript docs, setting the `types` option in your `tsconfig` will cause TypeScript to not automatically include `@types/`-packages.
https://www.typescriptlang.org/tsconfig#types

So you would have to add `@types/nameof` (which you have installed according to the typescript-nameof guide) to the `types` setting, too:
```json
{
  "compilerOptions": {
    "types": [
      "vite/client",
      "@types/nameof"
    ]
  }
}
```

Once this is done, TypeScript won't report errors to vscode anymore.

However, there are still the errors reported by `vite` (the screenshots of the terminal you posted).
In order to use `typescript-nameof` you need an implementation of TypeScript which supports custom transformers (`ttypescript` or `ts-patch` (recommended options)).

Install `ts-patch`:
```sh
npm install --save-dev ts-patch@2
ts-patch install
```

> ***Note:***  
> `ts-patch@2` is the last version to support TypeScript v4 - the version of TypeScript you use in your playground. If you want to use the latest version of `ts-patch` you would have to also switch to TypeScript v5+.

After this, the preview of `vite` will work and also the builds of `vite build` will be founctional.

I will keep this issue open and change the title accordingly.
Please let me know if you need further help related to using this project with `vite`.

**Comment by nemu69** [comment]
Awesome, thats works, thanks for your support ✅
